#!/bin/bash

if [ "$#" -ne 2 ];
  then
    echo "Usage:"
    echo "wb-cc2652p-flasher <module number> <firmware file>"
    exit 1
fi

if [[ $1 == '1' ]]; then
    RTS_GPIO=36
elif [[ $1 == '2' ]]; then
    RTS_GPIO=84
elif [[ $1 == '3' ]]; then
    RTS_GPIO=138
elif [[ $1 == '4' ]]; then
    RTS_GPIO=270
else
    echo "Incorrect module number, must me 1-4"
    exit 1
fi

if [ ! -e /sys/class/gpio/gpio$RTS_GPIO ]
then
    echo $RTS_GPIO > /sys/class/gpio/export
    echo out > /sys/class/gpio/gpio$RTS_GPIO/direction
fi

if [ -e $2 ]
then
    echo "Using RTS_GPIO $RTS_GPIO"
    echo 1 > /sys/class/gpio/gpio$RTS_GPIO/value
    sleep 1
    echo 0 > /sys/class/gpio/gpio$RTS_GPIO/value
    sleep 1

    cc2538-bsl.py -evw -p /dev/ttyMOD$1 $2
else
    echo "Firware file *.hex not found"
fi
