#!/bin/bash

set -e

if [ "$#" -ne 2 ];
  then
    echo "Usage: wb-cc2652p-flasher <module number> <firmware file>"
    exit 1
fi

# find platform-dependant MOD# RTS pin number
RTS_GPIO=$(gpiofind "MOD$1 RTS" | awk '{print $2}')

if [ -z "$RTS_GPIO" ]; then
    echo "Cannot find GPIO RTS for module $1"
    exit 1
fi

if [ ! -e "/sys/class/gpio/gpio$RTS_GPIO" ]
then
    echo "$RTS_GPIO" > /sys/class/gpio/export
    echo "out" > "/sys/class/gpio/gpio$RTS_GPIO/direction"
fi

if [ -e "$2" ]
then
    # switch zigbee chip into flashing mode using RTS pin
    echo "Using RTS_GPIO $RTS_GPIO"
    echo 1 > "/sys/class/gpio/gpio$RTS_GPIO/value"
    sleep 1
    echo 0 > "/sys/class/gpio/gpio$RTS_GPIO/value"
    sleep 1

    cc2538-bsl.py -evw -p "/dev/ttyMOD$1" "$2"
else
    echo "Firmware file $2 not found"
fi
